#!/bin/bash 
                function quit {
                   exit
                }  
                function e {
                    echo $1 
                }  
                e Hello
                e World
                quit
                echo foo 
function readtemp { echo "select * from tempdb.temp order by timestamp desc limit 1"|mysql -sN -uroot -p1234|awk '{print $3}' ;}

readtemp () { n="$1" ;echo "select * from tempdb.temp order by timestamp desc limit 1"|mysql -sN -uroot -p1234|awk '{print $'$n'}' ;}
